# Genera la migrazione 1200 (catalogo patologie) a partire dai dati sotto.
# Codici di esenzione: DPCM 12/1/2017 All. 7 (malattie rare) e All. 8 (croniche),
# verificati incrociando almeno due elenchi regionali; ORPHAcode da Orphanet.
import json, sys

def P(codice, nome, tipo, area, esenzione, orpha, descrizione, allarme, diagnosi, follow_up, specialisti,
      emergenza=None, note=None, icd=(), sinonimi=(), fonti=()):
    return dict(codice=codice, nome=nome, tipo=tipo, area=area, esenzione=esenzione, orpha=orpha,
                descrizione=descrizione, allarme=list(allarme), diagnosi=diagnosi, follow_up=list(follow_up),
                specialisti=specialisti, emergenza=emergenza, note=note, icd=list(icd), sinonimi=list(sinonimi),
                fonti=[{'titolo': t, 'url': u} for t, u in fonti])

ESPGHAN = ('Husby S. et al. Linee guida ESPGHAN 2020 per la diagnosi di celiachia, J Pediatr Gastroenterol Nutr 2020', 'https://doi.org/10.1097/MPG.0000000000002497')
AHA_KAW = ('McCrindle B.W. et al. Diagnosis, Treatment and Long-Term Management of Kawasaki Disease, AHA, Circulation 2017', 'https://doi.org/10.1161/CIR.0000000000000484')
NF1_2021 = ('Legius E. et al. Criteri diagnostici rivisti per NF1, Genet Med 2021', 'https://doi.org/10.1038/s41436-021-01170-5')
TSC_2021 = ('Northrup H. et al. Criteri diagnostici e raccomandazioni di sorveglianza TSC 2021, Pediatr Neurol 2021', 'https://doi.org/10.1016/j.pediatrneurol.2021.07.011')
GHENT = ('Loeys B.L. et al. Nosologia di Ghent rivista per la sindrome di Marfan, J Med Genet 2010', 'https://doi.org/10.1136/jmg.2009.072785')
BWS = ('Brioude F. et al. Consensus internazionale sulla sindrome di Beckwith-Wiedemann, Nat Rev Endocrinol 2018', 'https://doi.org/10.1038/nrendo.2017.166')
GINA = ('Global Initiative for Asthma (GINA), report annuale', 'https://ginasthma.org')
JMF = ('Jeffrey Modell Foundation: 10 segni di allarme delle immunodeficienze primarie', 'https://info4pi.org')

PATOLOGIE = [
# ------------------------------------------------------------------ genetiche / cromosomiche
P('turner', 'Sindrome di Turner', 'rara', 'genetica', 'RN0680', 881,
  'Assenza totale o parziale di un cromosoma X nella femmina (45,X e mosaicismi).',
  ['Bassa statura con rallentamento della velocità di crescita', 'Linfedema di mani e piedi nella neonata',
   'Pterigio del collo, attaccatura bassa dei capelli', 'Pubertà ritardata o assente', 'Coartazione aortica, valvola aortica bicuspide'],
  'Cariotipo su sangue periferico (con un numero di cellule adeguato a riconoscere i mosaicismi).',
  ['Crescita e terapia con ormone della crescita', 'Valutazione cardiologica alla diagnosi e periodica',
   'Funzione tiroidea e screening della celiachia periodici', 'Udito', 'Ecografia renale alla diagnosi', 'Induzione puberale'],
  'Endocrinologo pediatra, cardiologo, genetista'),
P('x_fragile', 'Sindrome dell\'X fragile', 'rara', 'genetica', 'RN1330', 908,
  'Espansione della tripletta CGG nel gene FMR1: è la causa ereditaria più frequente di disabilità intellettiva.',
  ['Ritardo del linguaggio, disabilità intellettiva', 'Tratti autistici, iperattività', 'Orecchie grandi, volto allungato, macroorchidismo dopo la pubertà',
   'Familiari con disabilità intellettiva, insufficienza ovarica precoce o tremore/atassia in età adulta'],
  'Test molecolare del gene FMR1.',
  ['Neuropsichiatria infantile e riabilitazione (logopedia)', 'Valutazione cardiologica (prolasso mitralico)', 'Visita oculistica (strabismo)',
   'Consulenza genetica alla famiglia'],
  'Neuropsichiatra infantile, genetista', sinonimi=['Sindrome di Martin-Bell']),
P('prader_willi', 'Sindrome di Prader-Willi', 'rara', 'genetica', 'RN1310', 739,
  'Perdita di espressione dei geni paterni della regione 15q11-q13.',
  ['Ipotonia neonatale marcata con suzione debole', 'Criptorchidismo, genitali ipoplasici',
   'Dopo i primi anni: iperfagia e aumento di peso', 'Bassa statura, mani e piedi piccoli'],
  'Test di metilazione della regione 15q11-q13.',
  ['Controllo del peso e dell\'accesso al cibo', 'Ormone della crescita in centro', 'Valutazione delle apnee nel sonno prima e durante la terapia con GH',
   'Scoliosi, tiroide, glicemia'],
  'Endocrinologo pediatra, genetista, dietista',
  emergenza='Soglia del dolore alta e vomito raro: le patologie acute possono essere sottostimate. Dolore addominale dopo un\'abbuffata va valutato con urgenza (dilatazione gastrica).'),
P('angelman', 'Sindrome di Angelman', 'rara', 'genetica', 'RN1300', 72,
  'Perdita di funzione del gene UBE3A materno (regione 15q11-q13).',
  ['Grave ritardo dello sviluppo con linguaggio assente o minimo', 'Atassia, movimenti a scatti', 'Comportamento allegro con riso frequente',
   'Microcefalia acquisita', 'Epilessia, spesso nei primi anni', 'Disturbi del sonno'],
  'Test di metilazione 15q11-q13; se normale, analisi del gene UBE3A.',
  ['Neurologo ed EEG', 'Sonno', 'Scoliosi', 'Reflusso e alimentazione', 'Riabilitazione e comunicazione aumentativa'],
  'Neuropsichiatra infantile, genetista'),
P('williams', 'Sindrome di Williams', 'rara', 'genetica', 'RN1270', 904,
  'Microdelezione 7q11.23 che comprende il gene dell\'elastina.',
  ['Stenosi aortica sopravalvolare, stenosi delle arterie polmonari', 'Ipercalcemia nel lattante', 'Tratti del volto caratteristici',
   'Ritardo dello sviluppo con spiccata socievolezza', 'Ipertensione arteriosa'],
  'FISH o array-CGH per la regione 7q11.23.',
  ['Cardiologia e pressione arteriosa', 'Calcemia', 'Ecografia renale', 'Tiroide', 'Sviluppo e apprendimento'],
  'Cardiologo pediatra, genetista'),
P('noonan', 'Sindrome di Noonan', 'rara', 'genetica', 'RN1010', 648,
  'RASopatia a trasmissione autosomica dominante; il gene più spesso coinvolto è PTPN11.',
  ['Stenosi della valvola polmonare, cardiomiopatia ipertrofica', 'Bassa statura', 'Collo corto o pterigio, ptosi, ipertelorismo',
   'Criptorchidismo', 'Facilità al sanguinamento'],
  'Diagnosi clinica, confermata con pannello dei geni delle RASopatie.',
  ['Cardiologia periodica', 'Crescita (eventuale GH)', 'Studio della coagulazione prima di interventi', 'Vista, udito, sviluppo'],
  'Cardiologo pediatra, genetista, endocrinologo'),
P('marfan', 'Sindrome di Marfan', 'rara', 'genetica', 'RN1320', 558,
  'Malattia del tessuto connettivo dovuta a varianti del gene FBN1, autosomica dominante.',
  ['Statura alta con arti lunghi e dita affusolate', 'Petto escavato o carenato, scoliosi', 'Lussazione del cristallino, miopia elevata',
   'Dilatazione della radice aortica', 'Familiari con morte improvvisa o dissezione aortica'],
  'Criteri di Ghent rivisti (2010) e analisi del gene FBN1.',
  ['Ecocardiogramma periodico della radice aortica', 'Visita oculistica con lampada a fessura', 'Ortopedia (colonna)',
   'Idoneità sportiva valutata dal cardiologo'],
  'Cardiologo, oculista, genetista',
  emergenza='Dolore toracico o dorsale improvviso e intenso: sospettare la dissezione aortica, pronto soccorso.', fonti=[GHENT]),
P('down', 'Sindrome di Down', 'cronica', 'genetica', '065', 870,
  'Trisomia del cromosoma 21.',
  ['Diagnosi di solito prenatale o alla nascita', 'Ipotonia, tratti somatici caratteristici'],
  'Cariotipo.',
  ['Ecocardiogramma alla nascita', 'Funzione tiroidea annuale', 'Emocromo', 'Screening della celiachia', 'Udito e vista periodici',
   'Apnee notturne', 'Curve di crescita specifiche', 'Sintomi neurologici (instabilità atlanto-assiale)'],
  'Pediatra con équipe multidisciplinare, cardiologo, genetista', icd=['758.0'], sinonimi=['Trisomia 21']),
P('klinefelter', 'Sindrome di Klinefelter', 'cronica', 'genetica', '066', 484,
  'Cariotipo 47,XXY o varianti nel maschio.',
  ['Testicoli piccoli e di consistenza aumentata', 'Ginecomastia, sviluppo puberale incompleto', 'Difficoltà di linguaggio e di apprendimento', 'Statura alta'],
  'Cariotipo.',
  ['Endocrinologia in età puberale (testosterone)', 'Supporto scolastico', 'Fertilità in età adulta'],
  'Endocrinologo pediatra', icd=['758.7']),
P('digeorge', 'Sindrome da delezione 22q11.2 (DiGeorge)', 'rara', 'immunologia', 'RCG160', 567,
  'Microdelezione 22q11.2; compresa tra le immunodeficienze primarie.',
  ['Cardiopatia conotruncale (tetralogia di Fallot, interruzione dell\'arco aortico, truncus)', 'Ipocalcemia neonatale con convulsioni',
   'Palatoschisi o voce nasale (insufficienza velofaringea)', 'Infezioni ricorrenti', 'Ritardo del linguaggio'],
  'FISH o array-CGH per la regione 22q11.2; conta dei linfociti T.',
  ['Calcio e paratormone', 'Valutazione immunologica prima dei vaccini vivi', 'Cardiologia', 'Otorino e logopedia',
   'Neuropsichiatria (rischio psichiatrico in adolescenza)'],
  'Immunologo pediatra, cardiologo, genetista',
  emergenza='Convulsioni nel neonato o in corso di malattia: controllare la calcemia.', sinonimi=['Sindrome velo-cardio-facciale']),
P('cornelia_de_lange', 'Sindrome di Cornelia de Lange', 'rara', 'genetica', 'RN1410', 199,
  'Sindrome malformativa da varianti dei geni della coesina (più spesso NIPBL).',
  ['Ritardo di crescita pre e post natale', 'Sopracciglia folte e unite, ciglia lunghe', 'Anomalie degli arti superiori', 'Reflusso gastroesofageo importante',
   'Disabilità intellettiva'],
  'Diagnosi clinica (consensus internazionale) e test genetico.',
  ['Reflusso e alimentazione', 'Udito e vista', 'Cardiologia', 'Comportamento e sviluppo'],
  'Genetista, gastroenterologo, neuropsichiatra infantile'),
P('beckwith_wiedemann', 'Sindrome di Beckwith-Wiedemann', 'rara', 'genetica', 'RN0820', 116,
  'Disordine di crescita dovuto ad alterazioni della regione 11p15; aumenta il rischio di tumori embrionali.',
  ['Macroglossia', 'Onfalocele o ernia ombelicale', 'Macrosomia, emiipertrofia (lateralizzazione della crescita)', 'Ipoglicemia neonatale'],
  'Diagnosi clinica e test di metilazione 11p15.',
  ['Sorveglianza dei tumori embrionali (Wilms, epatoblastoma) con ecografia addominale periodica, secondo il protocollo del centro',
   'Glicemia nel periodo neonatale', 'Macroglossia: alimentazione, respiro, linguaggio'],
  'Genetista, oncologo pediatra', fonti=[BWS]),
# ------------------------------------------------------------------ tumori / facomatosi
P('nf1', 'Neurofibromatosi tipo 1', 'rara', 'genetica', 'RBG010', 636,
  'Malattia autosomica dominante del gene NF1; circa metà dei casi è de novo.',
  ['6 o più macchie caffellatte (oltre 5 mm prima della pubertà)', 'Lentiggini ascellari o inguinali', 'Neurofibromi, noduli di Lisch',
   'Disturbi dell\'apprendimento e dell\'attenzione', 'Pseudoartrosi della tibia'],
  'Criteri clinici rivisti (2021), con test genetico nei casi dubbi.',
  ['Controllo annuale con pressione arteriosa, crescita, pubertà, colonna', 'Visita oculistica annuale (glioma delle vie ottiche, soprattutto nei primi anni)',
   'Valutazione neuropsicologica'],
  'Centro per le neurofibromatosi, neurologo, oculista',
  emergenza='Crescita rapida o dolore di un neurofibroma, calo della vista o pubertà precoce: valutazione specialistica rapida.',
  sinonimi=['Malattia di von Recklinghausen'], fonti=[NF1_2021]),
P('sclerosi_tuberosa', 'Sclerosi tuberosa', 'rara', 'genetica', 'RN0750', 805,
  'Malattia autosomica dominante dei geni TSC1/TSC2 con amartomi in più organi.',
  ['Macchie ipomelanotiche (3 o più)', 'Spasmi infantili, epilessia', 'Rabdomiomi cardiaci all\'ecografia prenatale', 'Angiofibromi del volto, chiazza zigrinata'],
  'Criteri clinici (2021) e test genetico.',
  ['EEG nel lattante anche senza crisi', 'Risonanza encefalo periodica', 'Ecografia o RM renale', 'Ecocardiogramma', 'Visita oculistica',
   'Valutazione neuropsichiatrica (TAND)'],
  'Neurologo pediatra, centro per la sclerosi tuberosa',
  emergenza='Spasmi infantili: urgenza neurologica, il trattamento precoce migliora la prognosi.', fonti=[TSC_2021]),
P('wilms', 'Tumore di Wilms (nefroblastoma)', 'rara', 'oncologia', 'RB0010', 654,
  'Tumore renale embrionale, più frequente tra 1 e 5 anni.',
  ['Massa addominale spesso asintomatica, notata dai genitori', 'Ematuria', 'Ipertensione arteriosa'],
  'Ecografia addominale urgente, poi centro di oncologia pediatrica.',
  ['Oncologia pediatrica (centri AIEOP)', 'Funzione renale e pressione a lungo termine'],
  'Oncologo pediatra',
  emergenza='Non palpare ripetutamente la massa: rischio di rottura.',
  note='Sindromi predisponenti (Beckwith-Wiedemann, WAGR, emiipertrofia): sorveglianza ecografica periodica.'),
P('retinoblastoma', 'Retinoblastoma', 'rara', 'oncologia', 'RB0020', 790,
  'Tumore maligno della retina dell\'infanzia; le forme bilaterali sono di solito ereditarie (gene RB1).',
  ['Leucocoria (riflesso bianco della pupilla, anche nelle foto con il flash)', 'Strabismo di recente comparsa', 'Occhio rosso persistente'],
  'Test del riflesso rosso a ogni bilancio di salute; invio urgente all\'oculista.',
  ['Oncologia e oculistica pediatrica', 'Screening oculistico dei fratelli nelle forme ereditarie'],
  'Oculista pediatrico, oncologo pediatra'),
# ------------------------------------------------------------------ metaboliche / endocrine
P('fenilchetonuria', 'Fenilchetonuria', 'rara', 'metabolico', 'RCG040', 716,
  'Deficit dell\'enzima fenilalanina idrossilasi; individuata con lo screening neonatale esteso.',
  ['Positività allo screening neonatale', 'Se non trattata: ritardo dello sviluppo, odore di muffa, eczema'],
  'Screening neonatale esteso (Legge 167/2016), dosaggio della fenilalanina, test delle pterine, analisi genetica.',
  ['Dieta a ridotto contenuto di fenilalanina con alimenti speciali e miscele di aminoacidi', 'Fenilalanina nel sangue periodica', 'Centro metabolico'],
  'Centro per le malattie metaboliche ereditarie, dietista',
  note='L\'aspartame contiene fenilalanina. Nelle ragazze: programmare un\'eventuale gravidanza con il centro.',
  sinonimi=['PKU', 'Iperfenilalaninemia']),
P('galattosemia', 'Galattosemia', 'rara', 'metabolico', 'RCG060', 352,
  'Deficit dell\'enzima GALT: il galattosio del latte si accumula e danneggia fegato, reni, cervello e cristallino.',
  ['Nei primi giorni di alimentazione con latte: vomito, ittero, epatomegalia, letargia', 'Ipoglicemia', 'Sepsi da E. coli', 'Cataratta'],
  'Dosaggio dell\'attività GALT nel sangue e analisi genetica.',
  ['Dieta senza galattosio per tutta la vita', 'Centro metabolico', 'Sviluppo e linguaggio', 'Funzione ovarica nelle ragazze'],
  'Centro per le malattie metaboliche ereditarie',
  emergenza='Neonato con sospetto clinico: sospendere il latte (materno o formula a base di latte) e inviare in ospedale.'),
P('glicogenosi', 'Glicogenosi', 'rara', 'metabolico', 'RCG060', None,
  'Gruppo di difetti del metabolismo del glicogeno con interessamento epatico e/o muscolare.',
  ['Ipoglicemia a digiuno, epatomegalia, volto paffuto e bassa statura (forme epatiche, es. tipo 1)', 'Debolezza muscolare, crampi da sforzo (forme muscolari)',
   'Cardiomiopatia nel lattante (tipo 2, malattia di Pompe)'],
  'Esami biochimici e analisi genetica.',
  ['Dieta con pasti frequenti e amido di mais crudo nelle forme epatiche', 'Centro metabolico'],
  'Centro per le malattie metaboliche ereditarie',
  emergenza='Ipoglicemia durante malattie con digiuno o vomito: glucosio per via endovenosa in ospedale.'),
P('wilson', 'Malattia di Wilson', 'rara', 'metabolico', 'RC0150', 905,
  'Accumulo di rame da varianti del gene ATP7B, autosomico recessivo.',
  ['Transaminasi elevate senza spiegazione', 'Epatite, epatomegalia', 'Anemia emolitica', 'Disturbi neurologici o psichiatrici in adolescenza',
   'Anelli di Kayser-Fleischer'],
  'Ceruloplasmina, rame nelle urine delle 24 ore, analisi del gene ATP7B.',
  ['Chelanti o zinco a vita', 'Epatologo', 'Test dei fratelli'],
  'Epatologo pediatra'),
P('iperplasia_surrenalica', 'Iperplasia surrenalica congenita', 'rara', 'endocrino', 'RCG020', 418,
  'Difetti della sintesi del cortisolo, più spesso deficit della 21-idrossilasi.',
  ['Genitali ambigui nella neonata', 'A 1–3 settimane: vomito, scarso accrescimento, disidratazione (crisi con perdita di sali)',
   'Forme non classiche: pubarca precoce, crescita accelerata'],
  '17-idrossiprogesterone, analisi del gene CYP21A2.',
  ['Terapia con idrocortisone (e fludrocortisone nelle forme con perdita di sali)', 'Crescita ed età ossea', 'Endocrinologo pediatra'],
  'Endocrinologo pediatra',
  emergenza='Con febbre, vomito o trauma aumentare l\'idrocortisone secondo il piano scritto del centro; se vomita, idrocortisone per iniezione e pronto soccorso. Tenere con sé la carta di emergenza.',
  sinonimi=['Sindromi adrenogenitali congenite']),
P('puberta_precoce', 'Pubertà precoce centrale idiopatica', 'rara', 'endocrino', 'RC0040', None,
  'Attivazione anticipata dell\'asse ipotalamo-ipofisi-gonadi senza una causa organica.',
  ['Sviluppo del seno prima degli 8 anni nelle femmine', 'Aumento del volume dei testicoli prima dei 9 anni nei maschi', 'Accelerazione della statura'],
  'Età ossea, test di stimolo con GnRH, ecografia pelvica; risonanza encefalo (soprattutto nei maschi e nelle bambine molto piccole).',
  ['Terapia con analoghi del GnRH in centro', 'Crescita ed età ossea'],
  'Endocrinologo pediatra'),
P('deficit_gh', 'Deficit dell\'ormone della crescita (nanismo ipofisario)', 'cronica', 'endocrino', '039', None,
  'Insufficiente produzione di ormone della crescita da parte dell\'ipofisi.',
  ['Bassa statura con velocità di crescita ridotta (attraversamento dei percentili)', 'Nel neonato: ipoglicemia, micropene, ittero prolungato'],
  'IGF-1, età ossea, test di stimolo del GH, risonanza ipotalamo-ipofisaria.',
  ['Terapia con GH secondo la Nota AIFA 39', 'Crescita ogni 3–6 mesi'],
  'Endocrinologo pediatra', icd=['253.3']),
P('ipotiroidismo', 'Ipotiroidismo congenito e acquisito grave', 'cronica', 'endocrino', '027', None,
  'Insufficiente produzione di ormoni tiroidei; la forma congenita è individuata con lo screening neonatale.',
  ['Positività del TSH allo screening neonatale', 'Ittero prolungato, stipsi, ipotonia, macroglossia, ernia ombelicale', 'Nel bambino più grande: rallentamento della crescita, stanchezza'],
  'TSH e FT4.',
  ['Levotiroxina iniziata subito nella forma congenita', 'TSH e FT4 periodici', 'Sviluppo psicomotorio'],
  'Endocrinologo pediatra', icd=['243', '244']),
P('diabete_1', 'Diabete mellito', 'cronica', 'endocrino', '013', None,
  'Nel bambino è quasi sempre diabete di tipo 1, autoimmune.',
  ['Sete intensa e urine abbondanti', 'Enuresi comparsa dopo che il bambino era asciutto', 'Calo di peso, stanchezza',
   'Vomito, dolore addominale, respiro profondo (chetoacidosi)'],
  'Glicemia (anche capillare in ambulatorio) e chetoni appena c\'è il sospetto.',
  ['Centro di diabetologia pediatrica', 'Emoglobina glicata', 'Tiroide e celiachia periodiche', 'Vaccino antinfluenzale'],
  'Diabetologo pediatra',
  emergenza='Il sospetto di esordio è un\'urgenza: invio in ospedale il giorno stesso. In ipoglicemia: zuccheri rapidi o glucagone.', icd=['250']),
# ------------------------------------------------------------------ neurologiche / neuromuscolari
P('sma', 'Atrofia muscolare spinale (SMA)', 'rara', 'neuromuscolare', 'RFG050', 70,
  'Degenerazione dei motoneuroni da delezione del gene SMN1.',
  ['Ipotonia e debolezza dei muscoli prossimali', 'Riflessi assenti', 'Perdita di tappe motorie acquisite', 'Fascicolazioni della lingua', 'Respiro addominale paradosso'],
  'Test genetico SMN1; screening neonatale attivo in diverse Regioni.',
  ['Terapie modificanti la malattia in centro (nusinersen, risdiplam, terapia genica)', 'Funzione respiratoria', 'Nutrizione', 'Ortopedia'],
  'Centro neuromuscolare pediatrico',
  emergenza='Infezioni respiratorie: rischio di insufficienza respiratoria, valutazione precoce.'),
P('duchenne', 'Distrofia muscolare di Duchenne', 'rara', 'neuromuscolare', 'RFG080', 98896,
  'Distrofia muscolare legata all\'X da assenza di distrofina.',
  ['Ritardo del cammino, difficoltà a correre e salire le scale', 'Manovra di Gowers per rialzarsi da terra', 'Polpacci voluminosi',
   'CK molto elevate; transaminasi alte senza malattia epatica'],
  'CK, poi analisi del gene DMD.',
  ['Centro neuromuscolare: corticosteroidi e terapie specifiche', 'Cardiologia e funzione respiratoria periodiche', 'Ortopedia'],
  'Centro neuromuscolare pediatrico',
  emergenza='Anestesia: rischio di rabdomiolisi e iperkaliemia con succinilcolina e anestetici alogenati. Segnalarlo sempre.',
  note='Transaminasi alte in un maschio senza causa epatica: dosare le CK.'),
P('rett', 'Sindrome di Rett', 'rara', 'neuro', 'RF0040', 778,
  'Disturbo del neurosviluppo da varianti del gene MECP2, quasi sempre nelle femmine.',
  ['Sviluppo apparentemente normale nei primi 6–18 mesi, poi regressione', 'Perdita dell\'uso finalizzato delle mani con stereotipie',
   'Perdita del linguaggio', 'Rallentamento della crescita della testa', 'Irregolarità del respiro, epilessia'],
  'Criteri clinici e analisi del gene MECP2.',
  ['Neurologo', 'Scoliosi', 'Alimentazione', 'ECG (QT lungo)', 'Salute dell\'osso'],
  'Neuropsichiatra infantile'),
P('west', 'Sindrome di West (spasmi infantili)', 'rara', 'neuro', 'RF0140', None,
  'Encefalopatia epilettica del lattante, di solito con esordio tra 3 e 12 mesi.',
  ['Spasmi in flessione o estensione, spesso in serie al risveglio', 'Arresto o regressione dello sviluppo'],
  'EEG urgente (ipsaritmia), poi ricerca della causa.',
  ['Neurologo pediatra', 'Sviluppo psicomotorio'],
  'Neurologo pediatra',
  emergenza='Sospetti spasmi: EEG e valutazione neurologica in pochi giorni. Il ritardo del trattamento peggiora la prognosi.'),
P('dravet', 'Sindrome di Dravet', 'rara', 'neuro', 'RF0061', 33069,
  'Encefalopatia epilettica, nella maggior parte dei casi da varianti del gene SCN1A.',
  ['Nel primo anno: crisi febbrili prolungate o di un solo lato in un lattante sano', 'Crisi scatenate da febbre o caldo (anche il bagno)',
   'Poi crisi di più tipi e rallentamento dello sviluppo'],
  'Analisi del gene SCN1A.',
  ['Neurologo pediatra', 'Piano scritto per le crisi prolungate'],
  'Neurologo pediatra',
  emergenza='Crisi oltre 5 minuti: farmaco di soccorso secondo il piano e 118.',
  note='Da evitare i farmaci bloccanti dei canali del sodio (es. carbamazepina, lamotrigina). Le vaccinazioni non sono controindicate: va gestita la febbre.'),
P('lennox_gastaut', 'Sindrome di Lennox-Gastaut', 'rara', 'neuro', 'RF0130', 2382,
  'Encefalopatia epilettica con esordio di solito tra 3 e 5 anni.',
  ['Crisi di più tipi: toniche nel sonno, atoniche con cadute, assenze atipiche', 'Rallentamento cognitivo'],
  'EEG (punta-onda lenta).',
  ['Neurologo pediatra', 'Protezione dalle cadute (casco)'],
  'Neurologo pediatra', note='È esclusa dall\'esenzione 017 (epilessia) perché ha un proprio codice di malattia rara.'),
P('epilessia', 'Epilessia', 'cronica', 'neuro', '017', None,
  'Tendenza a crisi epilettiche ricorrenti non provocate.',
  ['Episodi parossistici ripetuti: perdita di coscienza, scosse, assenze', 'Crisi nel sonno'],
  'EEG, valutazione neurologica, eventuale risonanza.',
  ['Neurologo', 'Livelli dei farmaci quando indicato', 'Scuola: piano di somministrazione del farmaco di soccorso'],
  'Neurologo pediatra',
  emergenza='Crisi oltre 5 minuti: farmaco di soccorso secondo il piano e 118.', icd=['345'],
  note='Lennox-Gastaut esclusa (codice di malattia rara).'),
P('autismo', 'Disturbo dello spettro autistico', 'cronica', 'neuro', '044', None,
  'Disturbo del neurosviluppo con difficoltà di comunicazione sociale e comportamenti ripetitivi.',
  ['Assenza di indicazione per mostrare a 12–18 mesi', 'Mancata risposta al nome', 'Nessuna parola a 16 mesi o regressione del linguaggio',
   'Scarso contatto oculare, gioco ripetitivo'],
  'Strumenti di screening ai bilanci (es. M-CHAT-R tra 16 e 30 mesi); diagnosi in neuropsichiatria infantile.',
  ['Neuropsichiatria infantile e intervento precoce', 'Sonno e alimentazione'],
  'Neuropsichiatra infantile', icd=['299.0'],
  note='Rientra nel codice 044 (ICD-9-CM 299.0 disturbo autistico). I vaccini non causano autismo.'),
# ------------------------------------------------------------------ sangue / immunità
P('talassemia', 'Talassemia major e intermedia', 'rara', 'ematologia', 'RDG010', 848,
  'Anemia ereditaria da ridotta sintesi delle catene beta dell\'emoglobina.',
  ['Tra 6 e 24 mesi: pallore, irritabilità, scarsa crescita, milza e fegato ingranditi', 'Anemia microcitica con ferritina normale o alta'],
  'Emocromo, elettroforesi o HPLC dell\'emoglobina, analisi genetica; test dei genitori.',
  ['Trasfusioni regolari e chelazione del ferro in centro', 'Vaccinazioni complete, comprese quelle per l\'asplenia se splenectomizzati'],
  'Centro di ematologia pediatrica (talassemie)',
  note='Il portatore sano (trait talassemico) non ha diritto all\'esenzione: va distinto dalla carenza di ferro.',
  sinonimi=['Anemia mediterranea', 'Morbo di Cooley']),
P('drepanocitosi', 'Drepanocitosi (anemia falciforme)', 'rara', 'ematologia', 'RDG010', 232,
  'Emoglobinopatia con globuli rossi a falce che ostruiscono i piccoli vasi.',
  ['Dattilite nel lattante (mani e piedi gonfi e dolenti)', 'Crisi dolorose', 'Anemia emolitica', 'Infezioni gravi'],
  'HPLC o elettroforesi dell\'emoglobina.',
  ['Profilassi con penicillina nei primi anni', 'Vaccinazioni (pneumococco, meningococchi)', 'Doppler transcranico annuale', 'Centro di ematologia'],
  'Ematologo pediatra',
  emergenza='Febbre: valutazione urgente (rischio di sepsi). Dolore toracico con febbre, pallore con milza che aumenta, deficit neurologico: pronto soccorso.'),
P('emofilia', 'Emofilia A e B', 'rara', 'ematologia', 'RDG020', 98878,
  'Deficit ereditario, legato all\'X, del fattore VIII (A) o IX (B) della coagulazione.',
  ['Lividi estesi quando il bambino inizia a muoversi', 'Sanguinamento prolungato dopo prelievi o circoncisione', 'Emartro (articolazione gonfia e dolente)',
   'Parenti maschi da parte di madre con emofilia'],
  'aPTT allungato, dosaggio dei fattori VIII e IX.',
  ['Centro emofilia: profilassi con fattore o farmaci non sostitutivi', 'Vaccinazioni con le modalità indicate dal centro (ago sottile, compressione prolungata)',
   'Evitare farmaci per via intramuscolare, aspirina e FANS'],
  'Centro emofilia',
  emergenza='Trauma cranico, emartro o sanguinamento: terapia secondo il piano del centro e contatto immediato con il centro.',
  note='Comprende i difetti ereditari della coagulazione (RDG020).'),
P('immunodeficienze', 'Immunodeficienze primarie (errori congeniti dell\'immunità)', 'rara', 'immunologia', 'RCG160', None,
  'Difetti congeniti del sistema immunitario con infezioni ricorrenti, gravi o insolite.',
  ['4 o più otiti in un anno', '2 o più polmoniti in un anno', 'Antibiotici per 2 mesi con scarso effetto', 'Scarso accrescimento',
   'Ascessi profondi ricorrenti', 'Candidosi persistente oltre l\'anno', 'Familiari con immunodeficienza'],
  'Emocromo con formula, immunoglobuline, sottopopolazioni linfocitarie, risposte ai vaccini.',
  ['Immunologo pediatra', 'Vaccini vivi solo dopo parere dell\'immunologo'],
  'Immunologo pediatra',
  emergenza='Febbre in un bambino con immunodeficienza grave: valutazione urgente.', fonti=[JMF]),
P('febbre_mediterranea', 'Febbre mediterranea familiare', 'rara', 'immunologia', 'RCG161', 342,
  'Malattia autoinfiammatoria del gene MEFV, la più frequente delle febbri periodiche ereditarie.',
  ['Febbre di 1–3 giorni che si ripete', 'Dolore addominale, toracico o articolare durante gli episodi', 'Origine mediterranea orientale'],
  'Criteri clinici e analisi del gene MEFV; indici di infiammazione durante e fuori dalle crisi.',
  ['Colchicina', 'Proteinuria periodica (amiloidosi)'],
  'Reumatologo pediatra', note='Il codice RCG161 comprende anche altre sindromi autoinfiammatorie ereditarie.'),
# ------------------------------------------------------------------ apparati
P('celiachia', 'Malattia celiaca', 'cronica', 'gastro', '059', 555,
  'Enteropatia autoimmune scatenata dal glutine.',
  ['Diarrea cronica, distensione addominale, scarsa crescita', 'Anemia da carenza di ferro che non risponde', 'Transaminasi alte, bassa statura, difetti dello smalto, afte ricorrenti',
   'Gruppi a rischio: familiari di primo grado, diabete tipo 1, tiroidite, Down, Turner, Williams, deficit di IgA'],
  'Anticorpi anti-transglutaminasi IgA con IgA totali, mentre il bambino mangia glutine. Linee guida ESPGHAN 2020: diagnosi senza biopsia se anti-transglutaminasi ≥10 volte il limite e anticorpi antiendomisio positivi su un secondo prelievo.',
  ['Dieta senza glutine per tutta la vita', 'Anticorpi dopo 6–12 mesi, poi annuali', 'Crescita'],
  'Gastroenterologo pediatra', icd=['579.0', '694.0'], fonti=[ESPGHAN],
  note='L\'esenzione 059 comprende anche la dermatite erpetiforme (ICD-9-CM 694.0).'),
P('mici', 'Malattia di Crohn e colite ulcerosa', 'cronica', 'gastro', '009', None,
  'Malattie infiammatorie croniche intestinali.',
  ['Diarrea con sangue che persiste', 'Dolore addominale, calo di peso', 'Rallentamento della crescita, pubertà ritardata', 'Ragadi o fistole perianali', 'Anemia'],
  'Calprotectina fecale, indici di infiammazione, endoscopia.',
  ['Gastroenterologo pediatra', 'Crescita e pubertà'],
  'Gastroenterologo pediatra', icd=['555', '556']),
P('hirschsprung', 'Malattia di Hirschsprung', 'rara', 'gastro', 'RN0200', 388,
  'Assenza delle cellule gangliari nel tratto finale del colon.',
  ['Mancata emissione del meconio nelle prime 48 ore', 'Distensione addominale, vomito biliare', 'Stipsi ostinata fin dalla nascita'],
  'Biopsia rettale per suzione, clisma opaco, manometria.',
  ['Chirurgo pediatra', 'Continenza e stipsi dopo l\'intervento'],
  'Chirurgo pediatra',
  emergenza='Febbre, pancia gonfia e diarrea maleodorante (enterocolite), anche dopo l\'intervento: urgenza.',
  note='Più frequente nella sindrome di Down.'),
P('atresia_biliare', 'Atresia delle vie biliari', 'rara', 'gastro', 'RN0210', 30391,
  'Ostruzione progressiva delle vie biliari nelle prime settimane di vita.',
  ['Ittero oltre le 2 settimane di vita (3 se allattato al seno)', 'Feci chiare o acoliche', 'Urine scure', 'Fegato ingrandito'],
  'Bilirubina diretta o coniugata nell\'ittero prolungato, ecografia; intervento di Kasai entro i primi 2 mesi migliora la prognosi.',
  ['Epatologo pediatra in centro trapianti', 'Vitamine liposolubili'],
  'Epatologo pediatra',
  emergenza='Febbre dopo l\'intervento di Kasai: sospettare la colangite.',
  note='La carta colorimetrica delle feci aiuta i genitori a riconoscere le feci chiare.'),
P('atresia_esofagea', 'Atresia esofagea', 'rara', 'gastro', 'RNG251', 1199,
  'Interruzione della continuità dell\'esofago, spesso con fistola tracheo-esofagea.',
  ['Polidramnios in gravidanza', 'Neonato con molta saliva, tosse o cianosi al primo pasto', 'Impossibile far passare il sondino nello stomaco'],
  'Sondino e radiografia alla nascita.',
  ['Reflusso, restringimento dell\'anastomosi, tracheomalacia', 'Crescita', 'Ricerca di altre anomalie (associazione VACTERL)'],
  'Chirurgo pediatra, gastroenterologo'),
P('fibrosi_cistica', 'Fibrosi cistica', 'cronica', 'respiratorio', '018', 586,
  'Malattia autosomica recessiva del gene CFTR che colpisce polmoni e pancreas.',
  ['Positività allo screening neonatale', 'Ileo da meconio', 'Scarsa crescita con appetito conservato, feci grasse', 'Tosse cronica, infezioni respiratorie',
   'Sudore salato, polipi nasali'],
  'Screening neonatale (tripsina immunoreattiva) e test del sudore; analisi del gene CFTR.',
  ['Centro di riferimento per la fibrosi cistica (Legge 548/1993)', 'Modulatori del CFTR quando indicati', 'Fisioterapia respiratoria, enzimi pancreatici'],
  'Centro fibrosi cistica', icd=['277.0']),
P('asma', 'Asma', 'cronica', 'respiratorio', '007', None,
  'Infiammazione cronica delle vie aeree con broncospasmo reversibile.',
  ['Respiro sibilante ricorrente', 'Tosse notturna o da sforzo', 'Fame d\'aria con il gioco o lo sport'],
  'Spirometria con test di broncodilatazione (in genere dai 5–6 anni).',
  ['Piano d\'azione scritto', 'Tecnica inalatoria con distanziatore', 'Controllo dei sintomi e dei fattori scatenanti', 'Vaccino antinfluenzale'],
  'Pediatra, pneumologo o allergologo pediatra',
  emergenza='Crisi che non migliora con il broncodilatatore, difficoltà a parlare, labbra cianotiche: 118.', icd=['493'], fonti=[GINA]),
P('cardiopatie_congenite', 'Cardiopatie congenite', 'cronica', 'cardio', '0A02', None,
  'Malformazioni del cuore e dei grossi vasi presenti dalla nascita.',
  ['Soffio patologico', 'Cianosi', 'Affanno e sudorazione durante la poppata, scarsa crescita', 'Polsi femorali deboli (coartazione aortica)'],
  'Saturimetria neonatale, ecocardiogramma.',
  ['Cardiologo pediatra', 'Profilassi dell\'endocardite nei casi indicati dal cardiologo'],
  'Cardiologo pediatra', icd=['745', '746', '747'],
  note='Rientrano nel codice 0A02 «Affezioni del sistema circolatorio».'),
P('irc', 'Insufficienza renale cronica', 'cronica', 'nefro', '023', None,
  'Riduzione persistente della funzione renale; nel bambino spesso da malformazioni renali e delle vie urinarie.',
  ['Malformazioni renali alle ecografie prenatali', 'Infezioni urinarie ricorrenti', 'Scarsa crescita, poliuria', 'Ipertensione arteriosa'],
  'Creatinina con stima del filtrato, esame urine, ecografia.',
  ['Nefrologo pediatra', 'Pressione arteriosa, crescita, anemia, osso'],
  'Nefrologo pediatra', icd=['585']),
P('seu', 'Sindrome emolitico-uremica', 'rara', 'nefro', 'RD0010', None,
  'Anemia emolitica, piastrinopenia e danno renale acuto; nel bambino più spesso dopo infezione da E. coli produttore di Shiga-tossina.',
  ['Dopo una diarrea (spesso con sangue): pallore, poca urina, petecchie, edemi'],
  'Emocromo con ricerca degli schistociti, LDH, creatinina, ricerca dei batteri produttori di Shiga-tossina nelle feci.',
  ['Nefrologo pediatra: funzione renale e pressione a lungo termine'],
  'Nefrologo pediatra',
  emergenza='Sospetto clinico: invio urgente in ospedale.',
  note='Nella diarrea con sangue evitare i farmaci che riducono la motilità intestinale.'),
P('artrite_giovanile', 'Artrite idiopatica giovanile', 'cronica', 'reumatologia', '006', 92,
  'Artrite cronica che inizia prima dei 16 anni, di causa non nota.',
  ['Articolazione gonfia da oltre 6 settimane', 'Rigidità al mattino', 'Zoppia senza trauma'],
  'Diagnosi clinica di esclusione; ANA, indici di infiammazione.',
  ['Reumatologo pediatra', 'Controlli oculistici periodici con lampada a fessura: l\'uveite può non dare sintomi'],
  'Reumatologo pediatra', icd=['714.30', '714.32', '714.33'],
  note='Esente con il codice 006 (artrite reumatoide), che comprende le forme giovanili.'),
# ------------------------------------------------------------------ cute / occhio / scheletro
P('osteogenesi_imperfetta', 'Osteogenesi imperfetta', 'rara', 'scheletro', 'RNG060', 666,
  'Fragilità ossea ereditaria, più spesso da varianti dei geni del collagene di tipo I.',
  ['Fratture con traumi minimi', 'Sclere bluastre', 'Ipoacusia', 'Denti fragili e opalescenti'],
  'Valutazione clinica e analisi genetica.',
  ['Bisfosfonati in centro nei casi indicati', 'Ortopedia', 'Udito'],
  'Centro per le malattie dell\'osso, ortopedico',
  note='In presenza di fratture multiple va considerata anche la diagnosi differenziale con il maltrattamento.'),
P('acondroplasia', 'Acondroplasia', 'rara', 'scheletro', 'RNG050', 15,
  'Displasia scheletrica da variante del gene FGFR3, la più comune causa di bassa statura disarmonica.',
  ['Arti corti soprattutto nei segmenti prossimali', 'Testa grande con bozze frontali', 'Mani «a tridente»'],
  'Clinica, radiografie, analisi del gene FGFR3.',
  ['Curve di crescita specifiche', 'Nel lattante: risonanza del forame magno e polisonnografia', 'Otiti, apnee, cifosi', 'Terapia con vosoritide in centro'],
  'Genetista, centro per le displasie scheletriche',
  emergenza='Lattante con apnee o ipotonia marcata: valutare la compressione cervico-midollare.'),
P('craniosinostosi', 'Sindromi con craniosinostosi', 'rara', 'scheletro', 'RNG030', None,
  'Chiusura precoce di una o più suture del cranio, qui nelle forme sindromiche (es. Apert, Crouzon).',
  ['Forma anomala del cranio (allungato, triangolare, asimmetrico)', 'Fontanella chiusa precocemente', 'Segni di ipertensione endocranica'],
  'Visita, ecografia o TC 3D, analisi genetica.',
  ['Neurochirurgia pediatrica e chirurgia cranio-facciale', 'Fondo dell\'occhio'],
  'Neurochirurgo pediatra', note='Distinguerla dalla plagiocefalia posizionale, molto più frequente e benigna.'),
P('epidermolisi_bollosa', 'Epidermolisi bollosa ereditaria', 'rara', 'dermatologia', 'RN0570', 79361,
  'Fragilità della cute e delle mucose con bolle ed erosioni dopo traumi minimi.',
  ['Bolle ed erosioni dalla nascita nelle zone di frizione', 'Lesioni della bocca'],
  'Biopsia cutanea (immunofluorescenza) e analisi genetica.',
  ['Dermatologo del centro', 'Medicazioni non adesive', 'Nutrizione e anemia'],
  'Dermatologo pediatra, centro per l\'epidermolisi bollosa', sinonimi=['Bambini farfalla']),
P('ittiosi', 'Ittiosi congenite', 'rara', 'dermatologia', 'RNG070', None,
  'Gruppo di disturbi ereditari della cheratinizzazione.',
  ['Neonato «collodion»', 'Desquamazione diffusa, cute arrossata'],
  'Clinica e analisi genetica.',
  ['Emollienti', 'Nel neonato: temperatura corporea e idratazione', 'Dermatologo'],
  'Dermatologo pediatra'),
P('cheratocono', 'Cheratocono', 'rara', 'oculistica', 'RF0280', None,
  'Assottigliamento progressivo della cornea, che assume una forma conica.',
  ['Vista che peggiora rapidamente in adolescenza', 'Astigmatismo che cambia spesso', 'Abitudine a strofinare gli occhi (allergici, Down)'],
  'Topografia corneale.',
  ['Oculista: cross-linking corneale per fermare la progressione'],
  'Oculista'),
P('retinite_pigmentosa', 'Retinite pigmentosa', 'rara', 'oculistica', 'RFG110', 791,
  'Distrofie ereditarie della retina con perdita progressiva dei fotorecettori.',
  ['Difficoltà a vedere al buio', 'Restringimento del campo visivo'],
  'Elettroretinogramma, analisi genetica.',
  ['Oculista del centro', 'Supporto per l\'ipovisione'],
  'Oculista'),
# ------------------------------------------------------------------ senza esenzione (rilevanti per il PLS)
P('kawasaki', 'Malattia di Kawasaki', 'rara', 'cardio', None, 2331,
  'Vasculite acuta dell\'infanzia, principale causa di cardiopatia acquisita nei Paesi sviluppati.',
  ['Febbre da 5 giorni o più', 'Congiuntivite senza secrezione', 'Labbra rosse e screpolate, lingua «a fragola»', 'Esantema',
   'Mani e piedi gonfi e arrossati, poi desquamazione', 'Linfonodo del collo ingrossato', 'Nel lattante: forme incomplete'],
  'Criteri clinici (AHA 2017), esami del sangue, ecocardiogramma.',
  ['Ecocardiogrammi programmati dopo la fase acuta', 'Vaccini vivi (morbillo, parotite, rosolia, varicella) rimandati di 11 mesi dopo le immunoglobuline'],
  'Cardiologo pediatra',
  emergenza='Sospetto: ricovero. Le immunoglobuline entro 10 giorni dall\'inizio della febbre riducono gli aneurismi coronarici.',
  note='Non compare nell\'elenco nazionale delle malattie rare esenti: verificare eventuali elenchi regionali.', fonti=[AHA_KAW]),
P('prematurita', 'Prematurità', 'cronica', 'neonatologia', '040', None,
  'Nascita prima delle 37 settimane; l\'esenzione 040 riguarda i neonati prematuri e immaturi secondo i limiti della norma.',
  ['Età gestazionale alla nascita', 'Complicanze neonatali in lettera di dimissione'],
  'Lettera di dimissione dalla neonatologia.',
  ['Crescita e sviluppo valutati sull\'età corretta fino a circa 2 anni', 'Follow-up oculistico (retinopatia) e dell\'udito',
   'Vaccinazioni secondo l\'età cronologica', 'Prevenzione del virus respiratorio sinciziale'],
  'Neonatologo (follow-up), pediatra'),
]

esc = lambda s: 'null' if s is None else "'" + s.replace("'", "''") + "'"
arr = lambda xs: "'{}'::text[]" if not xs else 'array[' + ', '.join(esc(x) for x in xs) + ']'

righe = []
for i, p in enumerate(PATOLOGIE):
    righe.append('(' + ', '.join([
        esc(p['codice']), esc(p['nome']), arr(p['sinonimi']), esc(p['tipo']), esc(p['area']), esc(p['esenzione']),
        'null' if p['orpha'] is None else str(p['orpha']), arr(p['icd']), esc(p['descrizione']), arr(p['allarme']),
        esc(p['diagnosi']), arr(p['follow_up']), esc(p['specialisti']), esc(p['emergenza']), esc(p['note']),
        esc(json.dumps(p['fonti'], ensure_ascii=False)) + '::jsonb', str((i + 1) * 10)]) + ')')

codici = [p['codice'] for p in PATOLOGIE]
assert len(codici) == len(set(codici)), 'codici duplicati'
assert all(p['codice'].isascii() for p in PATOLOGIE)
print('-- %d patologie: %d rare, %d croniche, %d senza esenzione' % (
    len(PATOLOGIE), sum(p['tipo'] == 'rara' for p in PATOLOGIE), sum(p['tipo'] == 'cronica' for p in PATOLOGIE),
    sum(p['esenzione'] is None for p in PATOLOGIE)), file=sys.stderr)
sys.stdout.write(',\n'.join(righe) + ';\n')
