-- =============================================================================
-- 1200 · Catalogo di malattie rare e patologie croniche, patologie del bambino
--
-- Scheda di consultazione per il pediatra: NON è uno strumento diagnostico e non
-- suggerisce diagnosi a partire dai dati del paziente (nessuna logica automatica,
-- per restare fuori dall'ambito dei dispositivi medici - Reg. UE 2017/745).
--
-- Codici di esenzione:
--   * malattie rare: DPCM 12/1/2017, Allegato 7 (codici R...), verificati
--     incrociando almeno due elenchi regionali che lo recepiscono;
--   * malattie croniche e invalidanti: DPCM 12/1/2017, Allegato 8 (codici numerici),
--     con i codici ICD-9-CM delle condizioni incluse.
-- ORPHAcode: nomenclatura Orphanet.
-- Il contenuto è generato da supabase/strumenti/genera_patologie.py (python3 ... > righe.sql).
-- =============================================================================

create table anagrafica.catalogo_patologie (
  codice          text primary key,
  nome            text not null,
  sinonimi        text[] not null default '{}',
  tipo            text not null check (tipo in ('rara', 'cronica')),
  area            text not null,
  esenzione       text,                 -- codice di esenzione (null = non esente a livello nazionale)
  orpha           integer,              -- ORPHAcode
  icd9cm          text[] not null default '{}',
  descrizione     text not null,
  segni_allarme   text[] not null default '{}',
  diagnosi        text not null,
  follow_up       text[] not null default '{}',
  specialisti     text not null,
  emergenza       text,
  note            text,
  fonti           jsonb not null default '[]',   -- [{titolo, url}] specifiche della patologia
  ordine          smallint not null default 0,
  check (tipo <> 'rara' or esenzione is null or esenzione ~ '^R[A-Z0-9]{5}$'),
  check (tipo <> 'cronica' or esenzione ~ '^0?[A-Z0-9]{3}$')
);
alter table anagrafica.catalogo_patologie enable row level security;
grant select on anagrafica.catalogo_patologie to authenticated;
create policy staff_legge_patologie on anagrafica.catalogo_patologie
  for select to authenticated using (sicurezza.is_staff());

insert into anagrafica.catalogo_patologie
  (codice, nome, sinonimi, tipo, area, esenzione, orpha, icd9cm, descrizione, segni_allarme,
   diagnosi, follow_up, specialisti, emergenza, note, fonti, ordine) values
('turner', 'Sindrome di Turner', '{}'::text[], 'rara', 'genetica', 'RN0680', 881, '{}'::text[], 'Assenza totale o parziale di un cromosoma X nella femmina (45,X e mosaicismi).', array['Bassa statura con rallentamento della velocità di crescita', 'Linfedema di mani e piedi nella neonata', 'Pterigio del collo, attaccatura bassa dei capelli', 'Pubertà ritardata o assente', 'Coartazione aortica, valvola aortica bicuspide'], 'Cariotipo su sangue periferico (con un numero di cellule adeguato a riconoscere i mosaicismi).', array['Crescita e terapia con ormone della crescita', 'Valutazione cardiologica alla diagnosi e periodica', 'Funzione tiroidea e screening della celiachia periodici', 'Udito', 'Ecografia renale alla diagnosi', 'Induzione puberale'], 'Endocrinologo pediatra, cardiologo, genetista', null, null, '[]'::jsonb, 10),
('x_fragile', 'Sindrome dell''X fragile', array['Sindrome di Martin-Bell'], 'rara', 'genetica', 'RN1330', 908, '{}'::text[], 'Espansione della tripletta CGG nel gene FMR1: è la causa ereditaria più frequente di disabilità intellettiva.', array['Ritardo del linguaggio, disabilità intellettiva', 'Tratti autistici, iperattività', 'Orecchie grandi, volto allungato, macroorchidismo dopo la pubertà', 'Familiari con disabilità intellettiva, insufficienza ovarica precoce o tremore/atassia in età adulta'], 'Test molecolare del gene FMR1.', array['Neuropsichiatria infantile e riabilitazione (logopedia)', 'Valutazione cardiologica (prolasso mitralico)', 'Visita oculistica (strabismo)', 'Consulenza genetica alla famiglia'], 'Neuropsichiatra infantile, genetista', null, null, '[]'::jsonb, 20),
('prader_willi', 'Sindrome di Prader-Willi', '{}'::text[], 'rara', 'genetica', 'RN1310', 739, '{}'::text[], 'Perdita di espressione dei geni paterni della regione 15q11-q13.', array['Ipotonia neonatale marcata con suzione debole', 'Criptorchidismo, genitali ipoplasici', 'Dopo i primi anni: iperfagia e aumento di peso', 'Bassa statura, mani e piedi piccoli'], 'Test di metilazione della regione 15q11-q13.', array['Controllo del peso e dell''accesso al cibo', 'Ormone della crescita in centro', 'Valutazione delle apnee nel sonno prima e durante la terapia con GH', 'Scoliosi, tiroide, glicemia'], 'Endocrinologo pediatra, genetista, dietista', 'Soglia del dolore alta e vomito raro: le patologie acute possono essere sottostimate. Dolore addominale dopo un''abbuffata va valutato con urgenza (dilatazione gastrica).', null, '[]'::jsonb, 30),
('angelman', 'Sindrome di Angelman', '{}'::text[], 'rara', 'genetica', 'RN1300', 72, '{}'::text[], 'Perdita di funzione del gene UBE3A materno (regione 15q11-q13).', array['Grave ritardo dello sviluppo con linguaggio assente o minimo', 'Atassia, movimenti a scatti', 'Comportamento allegro con riso frequente', 'Microcefalia acquisita', 'Epilessia, spesso nei primi anni', 'Disturbi del sonno'], 'Test di metilazione 15q11-q13; se normale, analisi del gene UBE3A.', array['Neurologo ed EEG', 'Sonno', 'Scoliosi', 'Reflusso e alimentazione', 'Riabilitazione e comunicazione aumentativa'], 'Neuropsichiatra infantile, genetista', null, null, '[]'::jsonb, 40),
('williams', 'Sindrome di Williams', '{}'::text[], 'rara', 'genetica', 'RN1270', 904, '{}'::text[], 'Microdelezione 7q11.23 che comprende il gene dell''elastina.', array['Stenosi aortica sopravalvolare, stenosi delle arterie polmonari', 'Ipercalcemia nel lattante', 'Tratti del volto caratteristici', 'Ritardo dello sviluppo con spiccata socievolezza', 'Ipertensione arteriosa'], 'FISH o array-CGH per la regione 7q11.23.', array['Cardiologia e pressione arteriosa', 'Calcemia', 'Ecografia renale', 'Tiroide', 'Sviluppo e apprendimento'], 'Cardiologo pediatra, genetista', null, null, '[]'::jsonb, 50),
('noonan', 'Sindrome di Noonan', '{}'::text[], 'rara', 'genetica', 'RN1010', 648, '{}'::text[], 'RASopatia a trasmissione autosomica dominante; il gene più spesso coinvolto è PTPN11.', array['Stenosi della valvola polmonare, cardiomiopatia ipertrofica', 'Bassa statura', 'Collo corto o pterigio, ptosi, ipertelorismo', 'Criptorchidismo', 'Facilità al sanguinamento'], 'Diagnosi clinica, confermata con pannello dei geni delle RASopatie.', array['Cardiologia periodica', 'Crescita (eventuale GH)', 'Studio della coagulazione prima di interventi', 'Vista, udito, sviluppo'], 'Cardiologo pediatra, genetista, endocrinologo', null, null, '[]'::jsonb, 60),
('marfan', 'Sindrome di Marfan', '{}'::text[], 'rara', 'genetica', 'RN1320', 558, '{}'::text[], 'Malattia del tessuto connettivo dovuta a varianti del gene FBN1, autosomica dominante.', array['Statura alta con arti lunghi e dita affusolate', 'Petto escavato o carenato, scoliosi', 'Lussazione del cristallino, miopia elevata', 'Dilatazione della radice aortica', 'Familiari con morte improvvisa o dissezione aortica'], 'Criteri di Ghent rivisti (2010) e analisi del gene FBN1.', array['Ecocardiogramma periodico della radice aortica', 'Visita oculistica con lampada a fessura', 'Ortopedia (colonna)', 'Idoneità sportiva valutata dal cardiologo'], 'Cardiologo, oculista, genetista', 'Dolore toracico o dorsale improvviso e intenso: sospettare la dissezione aortica, pronto soccorso.', null, '[{"titolo": "Loeys B.L. et al. Nosologia di Ghent rivista per la sindrome di Marfan, J Med Genet 2010", "url": "https://doi.org/10.1136/jmg.2009.072785"}]'::jsonb, 70),
('down', 'Sindrome di Down', array['Trisomia 21'], 'cronica', 'genetica', '065', 870, array['758.0'], 'Trisomia del cromosoma 21.', array['Diagnosi di solito prenatale o alla nascita', 'Ipotonia, tratti somatici caratteristici'], 'Cariotipo.', array['Ecocardiogramma alla nascita', 'Funzione tiroidea annuale', 'Emocromo', 'Screening della celiachia', 'Udito e vista periodici', 'Apnee notturne', 'Curve di crescita specifiche', 'Sintomi neurologici (instabilità atlanto-assiale)'], 'Pediatra con équipe multidisciplinare, cardiologo, genetista', null, null, '[]'::jsonb, 80),
('klinefelter', 'Sindrome di Klinefelter', '{}'::text[], 'cronica', 'genetica', '066', 484, array['758.7'], 'Cariotipo 47,XXY o varianti nel maschio.', array['Testicoli piccoli e di consistenza aumentata', 'Ginecomastia, sviluppo puberale incompleto', 'Difficoltà di linguaggio e di apprendimento', 'Statura alta'], 'Cariotipo.', array['Endocrinologia in età puberale (testosterone)', 'Supporto scolastico', 'Fertilità in età adulta'], 'Endocrinologo pediatra', null, null, '[]'::jsonb, 90),
('digeorge', 'Sindrome da delezione 22q11.2 (DiGeorge)', array['Sindrome velo-cardio-facciale'], 'rara', 'immunologia', 'RCG160', 567, '{}'::text[], 'Microdelezione 22q11.2; compresa tra le immunodeficienze primarie.', array['Cardiopatia conotruncale (tetralogia di Fallot, interruzione dell''arco aortico, truncus)', 'Ipocalcemia neonatale con convulsioni', 'Palatoschisi o voce nasale (insufficienza velofaringea)', 'Infezioni ricorrenti', 'Ritardo del linguaggio'], 'FISH o array-CGH per la regione 22q11.2; conta dei linfociti T.', array['Calcio e paratormone', 'Valutazione immunologica prima dei vaccini vivi', 'Cardiologia', 'Otorino e logopedia', 'Neuropsichiatria (rischio psichiatrico in adolescenza)'], 'Immunologo pediatra, cardiologo, genetista', 'Convulsioni nel neonato o in corso di malattia: controllare la calcemia.', null, '[]'::jsonb, 100),
('cornelia_de_lange', 'Sindrome di Cornelia de Lange', '{}'::text[], 'rara', 'genetica', 'RN1410', 199, '{}'::text[], 'Sindrome malformativa da varianti dei geni della coesina (più spesso NIPBL).', array['Ritardo di crescita pre e post natale', 'Sopracciglia folte e unite, ciglia lunghe', 'Anomalie degli arti superiori', 'Reflusso gastroesofageo importante', 'Disabilità intellettiva'], 'Diagnosi clinica (consensus internazionale) e test genetico.', array['Reflusso e alimentazione', 'Udito e vista', 'Cardiologia', 'Comportamento e sviluppo'], 'Genetista, gastroenterologo, neuropsichiatra infantile', null, null, '[]'::jsonb, 110),
('beckwith_wiedemann', 'Sindrome di Beckwith-Wiedemann', '{}'::text[], 'rara', 'genetica', 'RN0820', 116, '{}'::text[], 'Disordine di crescita dovuto ad alterazioni della regione 11p15; aumenta il rischio di tumori embrionali.', array['Macroglossia', 'Onfalocele o ernia ombelicale', 'Macrosomia, emiipertrofia (lateralizzazione della crescita)', 'Ipoglicemia neonatale'], 'Diagnosi clinica e test di metilazione 11p15.', array['Sorveglianza dei tumori embrionali (Wilms, epatoblastoma) con ecografia addominale periodica, secondo il protocollo del centro', 'Glicemia nel periodo neonatale', 'Macroglossia: alimentazione, respiro, linguaggio'], 'Genetista, oncologo pediatra', null, null, '[{"titolo": "Brioude F. et al. Consensus internazionale sulla sindrome di Beckwith-Wiedemann, Nat Rev Endocrinol 2018", "url": "https://doi.org/10.1038/nrendo.2017.166"}]'::jsonb, 120),
('nf1', 'Neurofibromatosi tipo 1', array['Malattia di von Recklinghausen'], 'rara', 'genetica', 'RBG010', 636, '{}'::text[], 'Malattia autosomica dominante del gene NF1; circa metà dei casi è de novo.', array['6 o più macchie caffellatte (oltre 5 mm prima della pubertà)', 'Lentiggini ascellari o inguinali', 'Neurofibromi, noduli di Lisch', 'Disturbi dell''apprendimento e dell''attenzione', 'Pseudoartrosi della tibia'], 'Criteri clinici rivisti (2021), con test genetico nei casi dubbi.', array['Controllo annuale con pressione arteriosa, crescita, pubertà, colonna', 'Visita oculistica annuale (glioma delle vie ottiche, soprattutto nei primi anni)', 'Valutazione neuropsicologica'], 'Centro per le neurofibromatosi, neurologo, oculista', 'Crescita rapida o dolore di un neurofibroma, calo della vista o pubertà precoce: valutazione specialistica rapida.', null, '[{"titolo": "Legius E. et al. Criteri diagnostici rivisti per NF1, Genet Med 2021", "url": "https://doi.org/10.1038/s41436-021-01170-5"}]'::jsonb, 130),
('sclerosi_tuberosa', 'Sclerosi tuberosa', '{}'::text[], 'rara', 'genetica', 'RN0750', 805, '{}'::text[], 'Malattia autosomica dominante dei geni TSC1/TSC2 con amartomi in più organi.', array['Macchie ipomelanotiche (3 o più)', 'Spasmi infantili, epilessia', 'Rabdomiomi cardiaci all''ecografia prenatale', 'Angiofibromi del volto, chiazza zigrinata'], 'Criteri clinici (2021) e test genetico.', array['EEG nel lattante anche senza crisi', 'Risonanza encefalo periodica', 'Ecografia o RM renale', 'Ecocardiogramma', 'Visita oculistica', 'Valutazione neuropsichiatrica (TAND)'], 'Neurologo pediatra, centro per la sclerosi tuberosa', 'Spasmi infantili: urgenza neurologica, il trattamento precoce migliora la prognosi.', null, '[{"titolo": "Northrup H. et al. Criteri diagnostici e raccomandazioni di sorveglianza TSC 2021, Pediatr Neurol 2021", "url": "https://doi.org/10.1016/j.pediatrneurol.2021.07.011"}]'::jsonb, 140),
('wilms', 'Tumore di Wilms (nefroblastoma)', '{}'::text[], 'rara', 'oncologia', 'RB0010', 654, '{}'::text[], 'Tumore renale embrionale, più frequente tra 1 e 5 anni.', array['Massa addominale spesso asintomatica, notata dai genitori', 'Ematuria', 'Ipertensione arteriosa'], 'Ecografia addominale urgente, poi centro di oncologia pediatrica.', array['Oncologia pediatrica (centri AIEOP)', 'Funzione renale e pressione a lungo termine'], 'Oncologo pediatra', 'Non palpare ripetutamente la massa: rischio di rottura.', 'Sindromi predisponenti (Beckwith-Wiedemann, WAGR, emiipertrofia): sorveglianza ecografica periodica.', '[]'::jsonb, 150),
('retinoblastoma', 'Retinoblastoma', '{}'::text[], 'rara', 'oncologia', 'RB0020', 790, '{}'::text[], 'Tumore maligno della retina dell''infanzia; le forme bilaterali sono di solito ereditarie (gene RB1).', array['Leucocoria (riflesso bianco della pupilla, anche nelle foto con il flash)', 'Strabismo di recente comparsa', 'Occhio rosso persistente'], 'Test del riflesso rosso a ogni bilancio di salute; invio urgente all''oculista.', array['Oncologia e oculistica pediatrica', 'Screening oculistico dei fratelli nelle forme ereditarie'], 'Oculista pediatrico, oncologo pediatra', null, null, '[]'::jsonb, 160),
('fenilchetonuria', 'Fenilchetonuria', array['PKU', 'Iperfenilalaninemia'], 'rara', 'metabolico', 'RCG040', 716, '{}'::text[], 'Deficit dell''enzima fenilalanina idrossilasi; individuata con lo screening neonatale esteso.', array['Positività allo screening neonatale', 'Se non trattata: ritardo dello sviluppo, odore di muffa, eczema'], 'Screening neonatale esteso (Legge 167/2016), dosaggio della fenilalanina, test delle pterine, analisi genetica.', array['Dieta a ridotto contenuto di fenilalanina con alimenti speciali e miscele di aminoacidi', 'Fenilalanina nel sangue periodica', 'Centro metabolico'], 'Centro per le malattie metaboliche ereditarie, dietista', null, 'L''aspartame contiene fenilalanina. Nelle ragazze: programmare un''eventuale gravidanza con il centro.', '[]'::jsonb, 170),
('galattosemia', 'Galattosemia', '{}'::text[], 'rara', 'metabolico', 'RCG060', 352, '{}'::text[], 'Deficit dell''enzima GALT: il galattosio del latte si accumula e danneggia fegato, reni, cervello e cristallino.', array['Nei primi giorni di alimentazione con latte: vomito, ittero, epatomegalia, letargia', 'Ipoglicemia', 'Sepsi da E. coli', 'Cataratta'], 'Dosaggio dell''attività GALT nel sangue e analisi genetica.', array['Dieta senza galattosio per tutta la vita', 'Centro metabolico', 'Sviluppo e linguaggio', 'Funzione ovarica nelle ragazze'], 'Centro per le malattie metaboliche ereditarie', 'Neonato con sospetto clinico: sospendere il latte (materno o formula a base di latte) e inviare in ospedale.', null, '[]'::jsonb, 180),
('glicogenosi', 'Glicogenosi', '{}'::text[], 'rara', 'metabolico', 'RCG060', null, '{}'::text[], 'Gruppo di difetti del metabolismo del glicogeno con interessamento epatico e/o muscolare.', array['Ipoglicemia a digiuno, epatomegalia, volto paffuto e bassa statura (forme epatiche, es. tipo 1)', 'Debolezza muscolare, crampi da sforzo (forme muscolari)', 'Cardiomiopatia nel lattante (tipo 2, malattia di Pompe)'], 'Esami biochimici e analisi genetica.', array['Dieta con pasti frequenti e amido di mais crudo nelle forme epatiche', 'Centro metabolico'], 'Centro per le malattie metaboliche ereditarie', 'Ipoglicemia durante malattie con digiuno o vomito: glucosio per via endovenosa in ospedale.', null, '[]'::jsonb, 190),
('wilson', 'Malattia di Wilson', '{}'::text[], 'rara', 'metabolico', 'RC0150', 905, '{}'::text[], 'Accumulo di rame da varianti del gene ATP7B, autosomico recessivo.', array['Transaminasi elevate senza spiegazione', 'Epatite, epatomegalia', 'Anemia emolitica', 'Disturbi neurologici o psichiatrici in adolescenza', 'Anelli di Kayser-Fleischer'], 'Ceruloplasmina, rame nelle urine delle 24 ore, analisi del gene ATP7B.', array['Chelanti o zinco a vita', 'Epatologo', 'Test dei fratelli'], 'Epatologo pediatra', null, null, '[]'::jsonb, 200),
('iperplasia_surrenalica', 'Iperplasia surrenalica congenita', array['Sindromi adrenogenitali congenite'], 'rara', 'endocrino', 'RCG020', 418, '{}'::text[], 'Difetti della sintesi del cortisolo, più spesso deficit della 21-idrossilasi.', array['Genitali ambigui nella neonata', 'A 1–3 settimane: vomito, scarso accrescimento, disidratazione (crisi con perdita di sali)', 'Forme non classiche: pubarca precoce, crescita accelerata'], '17-idrossiprogesterone, analisi del gene CYP21A2.', array['Terapia con idrocortisone (e fludrocortisone nelle forme con perdita di sali)', 'Crescita ed età ossea', 'Endocrinologo pediatra'], 'Endocrinologo pediatra', 'Con febbre, vomito o trauma aumentare l''idrocortisone secondo il piano scritto del centro; se vomita, idrocortisone per iniezione e pronto soccorso. Tenere con sé la carta di emergenza.', null, '[]'::jsonb, 210),
('puberta_precoce', 'Pubertà precoce centrale idiopatica', '{}'::text[], 'rara', 'endocrino', 'RC0040', null, '{}'::text[], 'Attivazione anticipata dell''asse ipotalamo-ipofisi-gonadi senza una causa organica.', array['Sviluppo del seno prima degli 8 anni nelle femmine', 'Aumento del volume dei testicoli prima dei 9 anni nei maschi', 'Accelerazione della statura'], 'Età ossea, test di stimolo con GnRH, ecografia pelvica; risonanza encefalo (soprattutto nei maschi e nelle bambine molto piccole).', array['Terapia con analoghi del GnRH in centro', 'Crescita ed età ossea'], 'Endocrinologo pediatra', null, null, '[]'::jsonb, 220),
('deficit_gh', 'Deficit dell''ormone della crescita (nanismo ipofisario)', '{}'::text[], 'cronica', 'endocrino', '039', null, array['253.3'], 'Insufficiente produzione di ormone della crescita da parte dell''ipofisi.', array['Bassa statura con velocità di crescita ridotta (attraversamento dei percentili)', 'Nel neonato: ipoglicemia, micropene, ittero prolungato'], 'IGF-1, età ossea, test di stimolo del GH, risonanza ipotalamo-ipofisaria.', array['Terapia con GH secondo la Nota AIFA 39', 'Crescita ogni 3–6 mesi'], 'Endocrinologo pediatra', null, null, '[]'::jsonb, 230),
('ipotiroidismo', 'Ipotiroidismo congenito e acquisito grave', '{}'::text[], 'cronica', 'endocrino', '027', null, array['243', '244'], 'Insufficiente produzione di ormoni tiroidei; la forma congenita è individuata con lo screening neonatale.', array['Positività del TSH allo screening neonatale', 'Ittero prolungato, stipsi, ipotonia, macroglossia, ernia ombelicale', 'Nel bambino più grande: rallentamento della crescita, stanchezza'], 'TSH e FT4.', array['Levotiroxina iniziata subito nella forma congenita', 'TSH e FT4 periodici', 'Sviluppo psicomotorio'], 'Endocrinologo pediatra', null, null, '[]'::jsonb, 240),
('diabete_1', 'Diabete mellito', '{}'::text[], 'cronica', 'endocrino', '013', null, array['250'], 'Nel bambino è quasi sempre diabete di tipo 1, autoimmune.', array['Sete intensa e urine abbondanti', 'Enuresi comparsa dopo che il bambino era asciutto', 'Calo di peso, stanchezza', 'Vomito, dolore addominale, respiro profondo (chetoacidosi)'], 'Glicemia (anche capillare in ambulatorio) e chetoni appena c''è il sospetto.', array['Centro di diabetologia pediatrica', 'Emoglobina glicata', 'Tiroide e celiachia periodiche', 'Vaccino antinfluenzale'], 'Diabetologo pediatra', 'Il sospetto di esordio è un''urgenza: invio in ospedale il giorno stesso. In ipoglicemia: zuccheri rapidi o glucagone.', null, '[]'::jsonb, 250),
('sma', 'Atrofia muscolare spinale (SMA)', '{}'::text[], 'rara', 'neuromuscolare', 'RFG050', 70, '{}'::text[], 'Degenerazione dei motoneuroni da delezione del gene SMN1.', array['Ipotonia e debolezza dei muscoli prossimali', 'Riflessi assenti', 'Perdita di tappe motorie acquisite', 'Fascicolazioni della lingua', 'Respiro addominale paradosso'], 'Test genetico SMN1; screening neonatale attivo in diverse Regioni.', array['Terapie modificanti la malattia in centro (nusinersen, risdiplam, terapia genica)', 'Funzione respiratoria', 'Nutrizione', 'Ortopedia'], 'Centro neuromuscolare pediatrico', 'Infezioni respiratorie: rischio di insufficienza respiratoria, valutazione precoce.', null, '[]'::jsonb, 260),
('duchenne', 'Distrofia muscolare di Duchenne', '{}'::text[], 'rara', 'neuromuscolare', 'RFG080', 98896, '{}'::text[], 'Distrofia muscolare legata all''X da assenza di distrofina.', array['Ritardo del cammino, difficoltà a correre e salire le scale', 'Manovra di Gowers per rialzarsi da terra', 'Polpacci voluminosi', 'CK molto elevate; transaminasi alte senza malattia epatica'], 'CK, poi analisi del gene DMD.', array['Centro neuromuscolare: corticosteroidi e terapie specifiche', 'Cardiologia e funzione respiratoria periodiche', 'Ortopedia'], 'Centro neuromuscolare pediatrico', 'Anestesia: rischio di rabdomiolisi e iperkaliemia con succinilcolina e anestetici alogenati. Segnalarlo sempre.', 'Transaminasi alte in un maschio senza causa epatica: dosare le CK.', '[]'::jsonb, 270),
('rett', 'Sindrome di Rett', '{}'::text[], 'rara', 'neuro', 'RF0040', 778, '{}'::text[], 'Disturbo del neurosviluppo da varianti del gene MECP2, quasi sempre nelle femmine.', array['Sviluppo apparentemente normale nei primi 6–18 mesi, poi regressione', 'Perdita dell''uso finalizzato delle mani con stereotipie', 'Perdita del linguaggio', 'Rallentamento della crescita della testa', 'Irregolarità del respiro, epilessia'], 'Criteri clinici e analisi del gene MECP2.', array['Neurologo', 'Scoliosi', 'Alimentazione', 'ECG (QT lungo)', 'Salute dell''osso'], 'Neuropsichiatra infantile', null, null, '[]'::jsonb, 280),
('west', 'Sindrome di West (spasmi infantili)', '{}'::text[], 'rara', 'neuro', 'RF0140', null, '{}'::text[], 'Encefalopatia epilettica del lattante, di solito con esordio tra 3 e 12 mesi.', array['Spasmi in flessione o estensione, spesso in serie al risveglio', 'Arresto o regressione dello sviluppo'], 'EEG urgente (ipsaritmia), poi ricerca della causa.', array['Neurologo pediatra', 'Sviluppo psicomotorio'], 'Neurologo pediatra', 'Sospetti spasmi: EEG e valutazione neurologica in pochi giorni. Il ritardo del trattamento peggiora la prognosi.', null, '[]'::jsonb, 290),
('dravet', 'Sindrome di Dravet', '{}'::text[], 'rara', 'neuro', 'RF0061', 33069, '{}'::text[], 'Encefalopatia epilettica, nella maggior parte dei casi da varianti del gene SCN1A.', array['Nel primo anno: crisi febbrili prolungate o di un solo lato in un lattante sano', 'Crisi scatenate da febbre o caldo (anche il bagno)', 'Poi crisi di più tipi e rallentamento dello sviluppo'], 'Analisi del gene SCN1A.', array['Neurologo pediatra', 'Piano scritto per le crisi prolungate'], 'Neurologo pediatra', 'Crisi oltre 5 minuti: farmaco di soccorso secondo il piano e 118.', 'Da evitare i farmaci bloccanti dei canali del sodio (es. carbamazepina, lamotrigina). Le vaccinazioni non sono controindicate: va gestita la febbre.', '[]'::jsonb, 300),
('lennox_gastaut', 'Sindrome di Lennox-Gastaut', '{}'::text[], 'rara', 'neuro', 'RF0130', 2382, '{}'::text[], 'Encefalopatia epilettica con esordio di solito tra 3 e 5 anni.', array['Crisi di più tipi: toniche nel sonno, atoniche con cadute, assenze atipiche', 'Rallentamento cognitivo'], 'EEG (punta-onda lenta).', array['Neurologo pediatra', 'Protezione dalle cadute (casco)'], 'Neurologo pediatra', null, 'È esclusa dall''esenzione 017 (epilessia) perché ha un proprio codice di malattia rara.', '[]'::jsonb, 310),
('epilessia', 'Epilessia', '{}'::text[], 'cronica', 'neuro', '017', null, array['345'], 'Tendenza a crisi epilettiche ricorrenti non provocate.', array['Episodi parossistici ripetuti: perdita di coscienza, scosse, assenze', 'Crisi nel sonno'], 'EEG, valutazione neurologica, eventuale risonanza.', array['Neurologo', 'Livelli dei farmaci quando indicato', 'Scuola: piano di somministrazione del farmaco di soccorso'], 'Neurologo pediatra', 'Crisi oltre 5 minuti: farmaco di soccorso secondo il piano e 118.', 'Lennox-Gastaut esclusa (codice di malattia rara).', '[]'::jsonb, 320),
('autismo', 'Disturbo dello spettro autistico', '{}'::text[], 'cronica', 'neuro', '044', null, array['299.0'], 'Disturbo del neurosviluppo con difficoltà di comunicazione sociale e comportamenti ripetitivi.', array['Assenza di indicazione per mostrare a 12–18 mesi', 'Mancata risposta al nome', 'Nessuna parola a 16 mesi o regressione del linguaggio', 'Scarso contatto oculare, gioco ripetitivo'], 'Strumenti di screening ai bilanci (es. M-CHAT-R tra 16 e 30 mesi); diagnosi in neuropsichiatria infantile.', array['Neuropsichiatria infantile e intervento precoce', 'Sonno e alimentazione'], 'Neuropsichiatra infantile', null, 'Rientra nel codice 044 (ICD-9-CM 299.0 disturbo autistico). I vaccini non causano autismo.', '[]'::jsonb, 330),
('talassemia', 'Talassemia major e intermedia', array['Anemia mediterranea', 'Morbo di Cooley'], 'rara', 'ematologia', 'RDG010', 848, '{}'::text[], 'Anemia ereditaria da ridotta sintesi delle catene beta dell''emoglobina.', array['Tra 6 e 24 mesi: pallore, irritabilità, scarsa crescita, milza e fegato ingranditi', 'Anemia microcitica con ferritina normale o alta'], 'Emocromo, elettroforesi o HPLC dell''emoglobina, analisi genetica; test dei genitori.', array['Trasfusioni regolari e chelazione del ferro in centro', 'Vaccinazioni complete, comprese quelle per l''asplenia se splenectomizzati'], 'Centro di ematologia pediatrica (talassemie)', null, 'Il portatore sano (trait talassemico) non ha diritto all''esenzione: va distinto dalla carenza di ferro.', '[]'::jsonb, 340),
('drepanocitosi', 'Drepanocitosi (anemia falciforme)', '{}'::text[], 'rara', 'ematologia', 'RDG010', 232, '{}'::text[], 'Emoglobinopatia con globuli rossi a falce che ostruiscono i piccoli vasi.', array['Dattilite nel lattante (mani e piedi gonfi e dolenti)', 'Crisi dolorose', 'Anemia emolitica', 'Infezioni gravi'], 'HPLC o elettroforesi dell''emoglobina.', array['Profilassi con penicillina nei primi anni', 'Vaccinazioni (pneumococco, meningococchi)', 'Doppler transcranico annuale', 'Centro di ematologia'], 'Ematologo pediatra', 'Febbre: valutazione urgente (rischio di sepsi). Dolore toracico con febbre, pallore con milza che aumenta, deficit neurologico: pronto soccorso.', null, '[]'::jsonb, 350),
('emofilia', 'Emofilia A e B', '{}'::text[], 'rara', 'ematologia', 'RDG020', 98878, '{}'::text[], 'Deficit ereditario, legato all''X, del fattore VIII (A) o IX (B) della coagulazione.', array['Lividi estesi quando il bambino inizia a muoversi', 'Sanguinamento prolungato dopo prelievi o circoncisione', 'Emartro (articolazione gonfia e dolente)', 'Parenti maschi da parte di madre con emofilia'], 'aPTT allungato, dosaggio dei fattori VIII e IX.', array['Centro emofilia: profilassi con fattore o farmaci non sostitutivi', 'Vaccinazioni con le modalità indicate dal centro (ago sottile, compressione prolungata)', 'Evitare farmaci per via intramuscolare, aspirina e FANS'], 'Centro emofilia', 'Trauma cranico, emartro o sanguinamento: terapia secondo il piano del centro e contatto immediato con il centro.', 'Comprende i difetti ereditari della coagulazione (RDG020).', '[]'::jsonb, 360),
('immunodeficienze', 'Immunodeficienze primarie (errori congeniti dell''immunità)', '{}'::text[], 'rara', 'immunologia', 'RCG160', null, '{}'::text[], 'Difetti congeniti del sistema immunitario con infezioni ricorrenti, gravi o insolite.', array['4 o più otiti in un anno', '2 o più polmoniti in un anno', 'Antibiotici per 2 mesi con scarso effetto', 'Scarso accrescimento', 'Ascessi profondi ricorrenti', 'Candidosi persistente oltre l''anno', 'Familiari con immunodeficienza'], 'Emocromo con formula, immunoglobuline, sottopopolazioni linfocitarie, risposte ai vaccini.', array['Immunologo pediatra', 'Vaccini vivi solo dopo parere dell''immunologo'], 'Immunologo pediatra', 'Febbre in un bambino con immunodeficienza grave: valutazione urgente.', null, '[{"titolo": "Jeffrey Modell Foundation: 10 segni di allarme delle immunodeficienze primarie", "url": "https://info4pi.org"}]'::jsonb, 370),
('febbre_mediterranea', 'Febbre mediterranea familiare', '{}'::text[], 'rara', 'immunologia', 'RCG161', 342, '{}'::text[], 'Malattia autoinfiammatoria del gene MEFV, la più frequente delle febbri periodiche ereditarie.', array['Febbre di 1–3 giorni che si ripete', 'Dolore addominale, toracico o articolare durante gli episodi', 'Origine mediterranea orientale'], 'Criteri clinici e analisi del gene MEFV; indici di infiammazione durante e fuori dalle crisi.', array['Colchicina', 'Proteinuria periodica (amiloidosi)'], 'Reumatologo pediatra', null, 'Il codice RCG161 comprende anche altre sindromi autoinfiammatorie ereditarie.', '[]'::jsonb, 380),
('celiachia', 'Malattia celiaca', '{}'::text[], 'cronica', 'gastro', '059', 555, array['579.0', '694.0'], 'Enteropatia autoimmune scatenata dal glutine.', array['Diarrea cronica, distensione addominale, scarsa crescita', 'Anemia da carenza di ferro che non risponde', 'Transaminasi alte, bassa statura, difetti dello smalto, afte ricorrenti', 'Gruppi a rischio: familiari di primo grado, diabete tipo 1, tiroidite, Down, Turner, Williams, deficit di IgA'], 'Anticorpi anti-transglutaminasi IgA con IgA totali, mentre il bambino mangia glutine. Linee guida ESPGHAN 2020: diagnosi senza biopsia se anti-transglutaminasi ≥10 volte il limite e anticorpi antiendomisio positivi su un secondo prelievo.', array['Dieta senza glutine per tutta la vita', 'Anticorpi dopo 6–12 mesi, poi annuali', 'Crescita'], 'Gastroenterologo pediatra', null, 'L''esenzione 059 comprende anche la dermatite erpetiforme (ICD-9-CM 694.0).', '[{"titolo": "Husby S. et al. Linee guida ESPGHAN 2020 per la diagnosi di celiachia, J Pediatr Gastroenterol Nutr 2020", "url": "https://doi.org/10.1097/MPG.0000000000002497"}]'::jsonb, 390),
('mici', 'Malattia di Crohn e colite ulcerosa', '{}'::text[], 'cronica', 'gastro', '009', null, array['555', '556'], 'Malattie infiammatorie croniche intestinali.', array['Diarrea con sangue che persiste', 'Dolore addominale, calo di peso', 'Rallentamento della crescita, pubertà ritardata', 'Ragadi o fistole perianali', 'Anemia'], 'Calprotectina fecale, indici di infiammazione, endoscopia.', array['Gastroenterologo pediatra', 'Crescita e pubertà'], 'Gastroenterologo pediatra', null, null, '[]'::jsonb, 400),
('hirschsprung', 'Malattia di Hirschsprung', '{}'::text[], 'rara', 'gastro', 'RN0200', 388, '{}'::text[], 'Assenza delle cellule gangliari nel tratto finale del colon.', array['Mancata emissione del meconio nelle prime 48 ore', 'Distensione addominale, vomito biliare', 'Stipsi ostinata fin dalla nascita'], 'Biopsia rettale per suzione, clisma opaco, manometria.', array['Chirurgo pediatra', 'Continenza e stipsi dopo l''intervento'], 'Chirurgo pediatra', 'Febbre, pancia gonfia e diarrea maleodorante (enterocolite), anche dopo l''intervento: urgenza.', 'Più frequente nella sindrome di Down.', '[]'::jsonb, 410),
('atresia_biliare', 'Atresia delle vie biliari', '{}'::text[], 'rara', 'gastro', 'RN0210', 30391, '{}'::text[], 'Ostruzione progressiva delle vie biliari nelle prime settimane di vita.', array['Ittero oltre le 2 settimane di vita (3 se allattato al seno)', 'Feci chiare o acoliche', 'Urine scure', 'Fegato ingrandito'], 'Bilirubina diretta o coniugata nell''ittero prolungato, ecografia; intervento di Kasai entro i primi 2 mesi migliora la prognosi.', array['Epatologo pediatra in centro trapianti', 'Vitamine liposolubili'], 'Epatologo pediatra', 'Febbre dopo l''intervento di Kasai: sospettare la colangite.', 'La carta colorimetrica delle feci aiuta i genitori a riconoscere le feci chiare.', '[]'::jsonb, 420),
('atresia_esofagea', 'Atresia esofagea', '{}'::text[], 'rara', 'gastro', 'RNG251', 1199, '{}'::text[], 'Interruzione della continuità dell''esofago, spesso con fistola tracheo-esofagea.', array['Polidramnios in gravidanza', 'Neonato con molta saliva, tosse o cianosi al primo pasto', 'Impossibile far passare il sondino nello stomaco'], 'Sondino e radiografia alla nascita.', array['Reflusso, restringimento dell''anastomosi, tracheomalacia', 'Crescita', 'Ricerca di altre anomalie (associazione VACTERL)'], 'Chirurgo pediatra, gastroenterologo', null, null, '[]'::jsonb, 430),
('fibrosi_cistica', 'Fibrosi cistica', '{}'::text[], 'cronica', 'respiratorio', '018', 586, array['277.0'], 'Malattia autosomica recessiva del gene CFTR che colpisce polmoni e pancreas.', array['Positività allo screening neonatale', 'Ileo da meconio', 'Scarsa crescita con appetito conservato, feci grasse', 'Tosse cronica, infezioni respiratorie', 'Sudore salato, polipi nasali'], 'Screening neonatale (tripsina immunoreattiva) e test del sudore; analisi del gene CFTR.', array['Centro di riferimento per la fibrosi cistica (Legge 548/1993)', 'Modulatori del CFTR quando indicati', 'Fisioterapia respiratoria, enzimi pancreatici'], 'Centro fibrosi cistica', null, null, '[]'::jsonb, 440),
('asma', 'Asma', '{}'::text[], 'cronica', 'respiratorio', '007', null, array['493'], 'Infiammazione cronica delle vie aeree con broncospasmo reversibile.', array['Respiro sibilante ricorrente', 'Tosse notturna o da sforzo', 'Fame d''aria con il gioco o lo sport'], 'Spirometria con test di broncodilatazione (in genere dai 5–6 anni).', array['Piano d''azione scritto', 'Tecnica inalatoria con distanziatore', 'Controllo dei sintomi e dei fattori scatenanti', 'Vaccino antinfluenzale'], 'Pediatra, pneumologo o allergologo pediatra', 'Crisi che non migliora con il broncodilatatore, difficoltà a parlare, labbra cianotiche: 118.', null, '[{"titolo": "Global Initiative for Asthma (GINA), report annuale", "url": "https://ginasthma.org"}]'::jsonb, 450),
('cardiopatie_congenite', 'Cardiopatie congenite', '{}'::text[], 'cronica', 'cardio', '0A02', null, array['745', '746', '747'], 'Malformazioni del cuore e dei grossi vasi presenti dalla nascita.', array['Soffio patologico', 'Cianosi', 'Affanno e sudorazione durante la poppata, scarsa crescita', 'Polsi femorali deboli (coartazione aortica)'], 'Saturimetria neonatale, ecocardiogramma.', array['Cardiologo pediatra', 'Profilassi dell''endocardite nei casi indicati dal cardiologo'], 'Cardiologo pediatra', null, 'Rientrano nel codice 0A02 «Affezioni del sistema circolatorio».', '[]'::jsonb, 460),
('irc', 'Insufficienza renale cronica', '{}'::text[], 'cronica', 'nefro', '023', null, array['585'], 'Riduzione persistente della funzione renale; nel bambino spesso da malformazioni renali e delle vie urinarie.', array['Malformazioni renali alle ecografie prenatali', 'Infezioni urinarie ricorrenti', 'Scarsa crescita, poliuria', 'Ipertensione arteriosa'], 'Creatinina con stima del filtrato, esame urine, ecografia.', array['Nefrologo pediatra', 'Pressione arteriosa, crescita, anemia, osso'], 'Nefrologo pediatra', null, null, '[]'::jsonb, 470),
('seu', 'Sindrome emolitico-uremica', '{}'::text[], 'rara', 'nefro', 'RD0010', null, '{}'::text[], 'Anemia emolitica, piastrinopenia e danno renale acuto; nel bambino più spesso dopo infezione da E. coli produttore di Shiga-tossina.', array['Dopo una diarrea (spesso con sangue): pallore, poca urina, petecchie, edemi'], 'Emocromo con ricerca degli schistociti, LDH, creatinina, ricerca dei batteri produttori di Shiga-tossina nelle feci.', array['Nefrologo pediatra: funzione renale e pressione a lungo termine'], 'Nefrologo pediatra', 'Sospetto clinico: invio urgente in ospedale.', 'Nella diarrea con sangue evitare i farmaci che riducono la motilità intestinale.', '[]'::jsonb, 480),
('artrite_giovanile', 'Artrite idiopatica giovanile', '{}'::text[], 'cronica', 'reumatologia', '006', 92, array['714.30', '714.32', '714.33'], 'Artrite cronica che inizia prima dei 16 anni, di causa non nota.', array['Articolazione gonfia da oltre 6 settimane', 'Rigidità al mattino', 'Zoppia senza trauma'], 'Diagnosi clinica di esclusione; ANA, indici di infiammazione.', array['Reumatologo pediatra', 'Controlli oculistici periodici con lampada a fessura: l''uveite può non dare sintomi'], 'Reumatologo pediatra', null, 'Esente con il codice 006 (artrite reumatoide), che comprende le forme giovanili.', '[]'::jsonb, 490),
('osteogenesi_imperfetta', 'Osteogenesi imperfetta', '{}'::text[], 'rara', 'scheletro', 'RNG060', 666, '{}'::text[], 'Fragilità ossea ereditaria, più spesso da varianti dei geni del collagene di tipo I.', array['Fratture con traumi minimi', 'Sclere bluastre', 'Ipoacusia', 'Denti fragili e opalescenti'], 'Valutazione clinica e analisi genetica.', array['Bisfosfonati in centro nei casi indicati', 'Ortopedia', 'Udito'], 'Centro per le malattie dell''osso, ortopedico', null, 'In presenza di fratture multiple va considerata anche la diagnosi differenziale con il maltrattamento.', '[]'::jsonb, 500),
('acondroplasia', 'Acondroplasia', '{}'::text[], 'rara', 'scheletro', 'RNG050', 15, '{}'::text[], 'Displasia scheletrica da variante del gene FGFR3, la più comune causa di bassa statura disarmonica.', array['Arti corti soprattutto nei segmenti prossimali', 'Testa grande con bozze frontali', 'Mani «a tridente»'], 'Clinica, radiografie, analisi del gene FGFR3.', array['Curve di crescita specifiche', 'Nel lattante: risonanza del forame magno e polisonnografia', 'Otiti, apnee, cifosi', 'Terapia con vosoritide in centro'], 'Genetista, centro per le displasie scheletriche', 'Lattante con apnee o ipotonia marcata: valutare la compressione cervico-midollare.', null, '[]'::jsonb, 510),
('craniosinostosi', 'Sindromi con craniosinostosi', '{}'::text[], 'rara', 'scheletro', 'RNG030', null, '{}'::text[], 'Chiusura precoce di una o più suture del cranio, qui nelle forme sindromiche (es. Apert, Crouzon).', array['Forma anomala del cranio (allungato, triangolare, asimmetrico)', 'Fontanella chiusa precocemente', 'Segni di ipertensione endocranica'], 'Visita, ecografia o TC 3D, analisi genetica.', array['Neurochirurgia pediatrica e chirurgia cranio-facciale', 'Fondo dell''occhio'], 'Neurochirurgo pediatra', null, 'Distinguerla dalla plagiocefalia posizionale, molto più frequente e benigna.', '[]'::jsonb, 520),
('epidermolisi_bollosa', 'Epidermolisi bollosa ereditaria', array['Bambini farfalla'], 'rara', 'dermatologia', 'RN0570', 79361, '{}'::text[], 'Fragilità della cute e delle mucose con bolle ed erosioni dopo traumi minimi.', array['Bolle ed erosioni dalla nascita nelle zone di frizione', 'Lesioni della bocca'], 'Biopsia cutanea (immunofluorescenza) e analisi genetica.', array['Dermatologo del centro', 'Medicazioni non adesive', 'Nutrizione e anemia'], 'Dermatologo pediatra, centro per l''epidermolisi bollosa', null, null, '[]'::jsonb, 530),
('ittiosi', 'Ittiosi congenite', '{}'::text[], 'rara', 'dermatologia', 'RNG070', null, '{}'::text[], 'Gruppo di disturbi ereditari della cheratinizzazione.', array['Neonato «collodion»', 'Desquamazione diffusa, cute arrossata'], 'Clinica e analisi genetica.', array['Emollienti', 'Nel neonato: temperatura corporea e idratazione', 'Dermatologo'], 'Dermatologo pediatra', null, null, '[]'::jsonb, 540),
('cheratocono', 'Cheratocono', '{}'::text[], 'rara', 'oculistica', 'RF0280', null, '{}'::text[], 'Assottigliamento progressivo della cornea, che assume una forma conica.', array['Vista che peggiora rapidamente in adolescenza', 'Astigmatismo che cambia spesso', 'Abitudine a strofinare gli occhi (allergici, Down)'], 'Topografia corneale.', array['Oculista: cross-linking corneale per fermare la progressione'], 'Oculista', null, null, '[]'::jsonb, 550),
('retinite_pigmentosa', 'Retinite pigmentosa', '{}'::text[], 'rara', 'oculistica', 'RFG110', 791, '{}'::text[], 'Distrofie ereditarie della retina con perdita progressiva dei fotorecettori.', array['Difficoltà a vedere al buio', 'Restringimento del campo visivo'], 'Elettroretinogramma, analisi genetica.', array['Oculista del centro', 'Supporto per l''ipovisione'], 'Oculista', null, null, '[]'::jsonb, 560),
('kawasaki', 'Malattia di Kawasaki', '{}'::text[], 'rara', 'cardio', null, 2331, '{}'::text[], 'Vasculite acuta dell''infanzia, principale causa di cardiopatia acquisita nei Paesi sviluppati.', array['Febbre da 5 giorni o più', 'Congiuntivite senza secrezione', 'Labbra rosse e screpolate, lingua «a fragola»', 'Esantema', 'Mani e piedi gonfi e arrossati, poi desquamazione', 'Linfonodo del collo ingrossato', 'Nel lattante: forme incomplete'], 'Criteri clinici (AHA 2017), esami del sangue, ecocardiogramma.', array['Ecocardiogrammi programmati dopo la fase acuta', 'Vaccini vivi (morbillo, parotite, rosolia, varicella) rimandati di 11 mesi dopo le immunoglobuline'], 'Cardiologo pediatra', 'Sospetto: ricovero. Le immunoglobuline entro 10 giorni dall''inizio della febbre riducono gli aneurismi coronarici.', 'Non compare nell''elenco nazionale delle malattie rare esenti: verificare eventuali elenchi regionali.', '[{"titolo": "McCrindle B.W. et al. Diagnosis, Treatment and Long-Term Management of Kawasaki Disease, AHA, Circulation 2017", "url": "https://doi.org/10.1161/CIR.0000000000000484"}]'::jsonb, 570),
('prematurita', 'Prematurità', '{}'::text[], 'cronica', 'neonatologia', '040', null, '{}'::text[], 'Nascita prima delle 37 settimane; l''esenzione 040 riguarda i neonati prematuri e immaturi secondo i limiti della norma.', array['Età gestazionale alla nascita', 'Complicanze neonatali in lettera di dimissione'], 'Lettera di dimissione dalla neonatologia.', array['Crescita e sviluppo valutati sull''età corretta fino a circa 2 anni', 'Follow-up oculistico (retinopatia) e dell''udito', 'Vaccinazioni secondo l''età cronologica', 'Prevenzione del virus respiratorio sinciziale'], 'Neonatologo (follow-up), pediatra', null, null, '[]'::jsonb, 580);

-- -----------------------------------------------------------------------------
-- Patologie del bambino (dato clinico: solo pseudo_id)
-- -----------------------------------------------------------------------------
create table clinica.patologie_paziente (
  id                 uuid primary key default gen_random_uuid(),
  pseudo_id          uuid not null references clinica.cartelle(pseudo_id),
  patologia          text not null references anagrafica.catalogo_patologie(codice),
  stato              text not null default 'sospetta' check (stato in ('sospetta', 'confermata', 'esclusa')),
  data_diagnosi      date,
  esenzione_attiva   boolean not null default false,   -- esenzione rilasciata dalla ASL
  centro_riferimento text,
  note               text,
  creato_il          timestamptz not null default now(),
  unique (pseudo_id, patologia)
);
create index on clinica.patologie_paziente (pseudo_id);
alter table clinica.patologie_paziente enable row level security;
grant select, insert, update, delete on clinica.patologie_paziente to authenticated;
create policy pediatra_gestisce_patologie on clinica.patologie_paziente
  for all to authenticated
  using (sicurezza.puo_accedere_clinica(pseudo_id))
  with check (sicurezza.puo_accedere_clinica(pseudo_id));
create trigger audit after insert or update or delete on clinica.patologie_paziente
  for each row execute function audit.traccia_modifica();
